-- Update material_items table to match Demand Details structure
ALTER TABLE public.material_items 
ADD COLUMN IF NOT EXISTS brand TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS model_part_no TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS unit TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS quantity NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS unit_price NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS required_date TEXT NOT NULL DEFAULT '';
